import Foundation

enum AppConstants {
    static let backendEndpoint = URL(string: "https://YOUR_BACKEND_URL.com/damagescope-ai")!
    static let privacyPolicyURL = URL(string: "https://github.com/lanray07/DamageScope-AI/blob/main/docs/PrivacyPolicy.md")!
    static let termsOfUseURL = URL(string: "https://www.apple.com/legal/internet-services/itunes/dev/stdeula/")!

    static let proMonthlyProductID = "com.damagescopeai.pro.monthly"
    static let proYearlyProductID = "com.damagescopeai.pro.yearly"
    static let businessMonthlyProductID = "com.damagescopeai.business.monthly"
    static let subscriptionProductIDs = [
        proMonthlyProductID,
        proYearlyProductID,
        businessMonthlyProductID
    ]

    static let disclaimers = [
        "AI findings are visual suggestions only",
        "Not insurance advice",
        "Not legal advice",
        "Not structural certification",
        "Not a repair cost guarantee",
        "AI findings must be reviewed by qualified professionals",
        "Urgent safety concerns should be checked by professionals immediately"
    ]

    static let internalAIPrompt = """
    You are DamageScope AI, an assistant for visual damage documentation. Review uploaded photos, damage type, location notes, and user descriptions. Identify visible, non-diagnostic signs of possible damage only. Do not guarantee cause, repair cost, insurance coverage, legal outcome, or structural safety. Use cautious language such as 'possible', 'visible sign of', 'appears to show', and 'recommend review by a qualified professional'. Return structured findings with severity, category, confidence, explanation, and suggested next action.
    """

    static let freePlanLimits = "2 damage cases/month, 10 photo scans/month, basic PDF report"
    static let reportFooter = "Generated by DamageScope AI"
}

extension String {
    var trimmed: String {
        trimmingCharacters(in: .whitespacesAndNewlines)
    }
}
